[[constraint]]
  name = "github.com/cenk/backoff"
  version = "1.1.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.9.6"

[[constraint]]
  name = "github.com/ory/dockertest"
  version = "3.1.6"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
